
#- platform: travisci
#  api_key: !secret travis_api
#  repository:
#    - HomeAssistant
#  branch:
#    - 'master'
#  monitored_conditions:
#    - last_build_state

- platform: cert_expiry
  host: !secret base_url
  port: 433 #433
